apiVersion: v1
metadata:
  name: kube-lego
data:
  # modify this to specify your address
  lego.email: "{{ .Values.email }}"
  # configure letencrypt's production api
  lego.url: "{{ .Values.api }}"
kind: ConfigMap